name: NDR Stack CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-lint-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io/<your-username>   # Change to your registry
      ZEKE_IMAGE: ${{ env.REGISTRY }}/zeek:latest
      SURICATA_IMAGE: ${{ env.REGISTRY }}/suricata:latest
      NAMESPACE: ndr-test

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---------------- Build Docker Images ----------------
      - name: Build Zeek Image
        run: docker build -t $ZEKE_IMAGE docker/zeek

      - name: Build Suricata Image
        run: docker build -t $SURICATA_IMAGE docker/suricata

      - name: Push Docker Images
        run: |
          docker push $ZEKE_IMAGE
          docker push $SURICATA_IMAGE

      # ---------------- Helm Lint ----------------
      - name: Helm Lint Zeek & Suricata
        run: helm lint charts/zeek charts/suricata

      # ---------------- Deploy to Kubernetes ----------------
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0  # match your cluster version

      - name: Create Test Namespace
        run: kubectl create namespace $NAMESPACE || true

      - name: Deploy Zeek via Helm
        run: helm upgrade --install zeek charts/zeek -n $NAMESPACE \
              --set image.repository=$ZEKE_IMAGE --set image.tag=latest

      - name: Deploy Suricata via Helm
        run: helm upgrade --install suricata charts/suricata -n $NAMESPACE \
              --set image.repository=$SURICATA_IMAGE --set image.tag=latest

      # ---------------- Verify Deployment ----------------
      - name: Wait for Pods Ready
        run: |
          kubectl rollout status deployment/zeek -n $NAMESPACE --timeout=2m
          kubectl rollout status deployment/suricata -n $NAMESPACE --timeout=2m

      # ---------------- Optional: Prometheus/Grafana ----------------
      - name: Apply Prometheus ServiceMonitor
        run: kubectl apply -f manifests/prometheus-servicemonitor.yaml -n $NAMESPACE

      - name: Deploy Grafana Dashboards
        run: |
          kubectl apply -f grafana/dashboards/ -n $NAMESPACE || echo "Add dashboards manually"
